**<h1 style = "color:darkblack;"><h1 style = "text-align:center;">ASSIGNMENT 1</h1></h1>**

**<h1 style = "color:black;"><h1 style = "text-align:center;">Basic Data Exploration and Cleaning Using Pandas</h1></h1>**

Basic data exploration and cleaning using Pandas helps in understanding and preparing data for analysis. Pandas is used to load datasets, view rows and columns, check data types, and generate summaries. It also helps in cleaning data by handling missing values, removing duplicates, renaming columns, and changing data types. Functions like head(), info(), describe(), dropna(), and fillna() are commonly used. After cleaning, the processed data can be saved for further analysis.

**Submitted By**

Priya_MMDU

**Role**

Data Engineer Fresher

**Import Required Libraries**

In [1]:
# Importing required library
import pandas as pd
print("Pandas library imported successfully")

Pandas library imported successfully

**<h1 style="color:blue;">Question 1: Load a CSV Dataset into a Pandas DataFrame</h1>**

**In this step, the CSV dataset is loaded into a Pandas DataFrame using Pandas library.**

In [3]:
csv_1 = pd.read_csv("C:\\Users\\ANUJ\\Documents\\sports-shoes.csv")
csv_1

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17745816,Lancer,Men Navy Blue Textile Running Non-Marking Shoes,4.0,6,1999.0,40.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/177...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""26.4cm"",""value_name"":""To...",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
1,17631178,Slazenger,Men White Woven Design Walking Shoes,3.7,127,3599.0,NaN,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":22,""2_stars"":10,""3_stars"":13,""4_star...",NaN,Tru███m R███il,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...","[""rw-17631178_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
2,13686682,Campus,Women White Mesh Walking Shoes,4.1,452,799.0,6.0,"""₹751.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":31,""2_stars"":18,""3_stars"":56,""4_star...",NaN,CAM███ AC███EWE█████████D,"[{""size"":""4"",""value"":""24.8cm"",""value_name"":""To...",NaN,Kha███ No███/25█████████ark███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
3,14480064,AfroJack,Men Black Textile Long Distance Running Non-Ma...,3.1,46,3995.0,80.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":14,""2_stars"":3,""3_stars"":6,""4_stars""...",NaN,WIN███INT███ATI██████,"[{""size"":""7"",""value"":""27.0cm"",""value_name"":""To...","[""rw-14480064_cae700""]","PLO███O. ███18,█████████RJE███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
4,10667394,Campus,Men Navy Blue Mesh Madrid Running Shoes,4.1,35,1499.0,37.0,"""₹944.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":3,""4_stars"":...",NaN,CAM███ AC███EWE█████████D,"[{""size"":""6"",""value"":""26.2cm"",""value_name"":""To...",NaN,Kha███ No███/25█████████ark███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
5,20071104,ADIDAS,Men Striped Amalgo M Running Shoes,4.5,149,4299.0,NaN,"""₹2,794.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":5,""2_stars"":3,""3_stars"":8,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20071104_cae700""]","1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
6,20072084,ADIDAS,Women Woven Design Runfalcon 3.0 Running Shoes,4.1,22,5999.0,NaN,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":4,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""4"",""value"":""22.5cm"",""value_name"":""To...","[""rw-20072084_cae700""]","1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
7,20071622,ADIDAS,Men Woven Design Znchill Running Shoes,3.2,21,11999.0,NaN,"""₹7,199.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":7,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20071622_cae700""]","1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
8,20071558,ADIDAS,Men Striped Pep Run M Running Shoes,4.1,231,3599.0,NaN,"""₹2,339.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":23,""2_stars"":14,""3_stars"":15,""4_star...",NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...",NaN,"1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
9,20071402,ADIDAS,Men Rokr Trail Trekking Shoes,4.5,149,4599.0,NaN,"""₹4,599.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":5,""2_stars"":5,""3_stars"":9,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20071402_cae700""]","1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
10,20070948,ADIDAS,Men Hitrail Mid WPN Trekking Shoes,4.1,52,5999.0,NaN,"""₹5,999.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":3,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20070948_cae700""]","1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
11,20070966,ADIDAS,Men Colourblocked Hikelacer Trekking Shoes,4.2,36,4799.0,NaN,"""₹2,879.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":5,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20070966_cae700""]","1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
12,20075460,UCLA,Men Olive Green Mesh Walking Non-Marking Shoes,3.7,3,4199.0,74.0,"""₹1,091.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,GUR███PA ███EST█████████NY,"[{""size"":""6"",""value"":""26.7cm"",""value_name"":""To...",NaN,"Plo███o. ███,Se█████████,UD███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
13,20071236,ADIDAS,Unisex Printed Predator Accuracy.4 Football Shoes,4.3,57,5299.0,NaN,"""₹5,299.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":5,""2_stars"":3,""3_stars"":2,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""4"",""value"":""22.5cm"",""value_name"":""To...",NaN,"1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
14,22054912,UNDER ARMOUR,Men Woven Design HOVR Infinite 4 Running Shoes,3.9,18,13499.0,NaN,"""₹13,499.00""",INR,http://assets.myntassets.com/assets/images/220...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
15,14208408,TRASE,Boys Navy Blue & White Sand-I Running Shoes,4.2,20,999.0,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/142...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""8-9Y"",""value"":""21.0cm"",""value_name"":...","[""rw-14208408_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
16,11441718,Duke,Men Black & Red Woven Design Running Shoes,4.2,50,2695.0,75.0,"""₹2,695.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":8,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""25.04cm"",""value_name"":""T...","[""rw-11441718_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
17,19324484,ELEVAR,Men ARC RACER All Purpose Sports Shoes,3.7,6,6490.0,NaN,"""₹6,490.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...","[""rw-19324484_cae700""]",NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
18,11627996,Yuuki,Men Black Mesh Running Shoes,4.2,56,2999.0,67.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":3,""2_stars"":3,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""26.7cm"",""value_name"":""To...","[""rw-11627996_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
19,11963938,FAUSTO,Men Grey Mesh Walking Shoes,3.9,8,899.0,1.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/119...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""25.5cm"",""value_name"":""To...","[""rw-11963938_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
20,19334944,ELEVAR,Men Black FLYBOLT Running Sports Shoes,3.2,11,5490.0,NaN,"""₹5,490.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...","[""rw-19334944_cae700""]",NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
21,11986876,FAUSTO,Men Blue Mesh Walking Shoes,4.3,9,899.0,1.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/119...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""25.5cm"",""value_name"":""To...","[""rw-11986876_cae700""]",NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
22,19334760,ELEVAR,Women Grey HYPERFLO Training & Gym Sports Shoes,3.0,4,5490.0,NaN,"""₹5,490.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""3"",""value"":""22.5cm"",""value_name"":""To...","[""rw-19334760_cae700""]",NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
23,19334942,ELEVAR,Men Grey FLYBOLT Running Sports Shoes,4.3,6,5490.0,NaN,"""₹5,490.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...","[""rw-19334942_cae700""]",NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
24,13484354,Puma,Women Black Eternity Nitro Running Shoes,4.3,19,12999.0,NaN,"""₹12,999.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Pum███por███Ind█████████td.█████████,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...","[""rw-13484354_cae700""]",Pum███por███Ind█████████d/ ███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
25,11960808,Campus,Men Navy Blue Running Shoes,4.2,76,1499.0,56.0,"""₹659.00""",INR,http://assets.myntassets.com/assets/images/119...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":10,""4_stars""...",NaN,CAM███ AC███EWE█████████D,"[{""size"":""6"",""value"":""26.2cm"",""value_name"":""To...","[""rw-11960808_cae700""]",Kha███ No███/25█████████ark███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
26,19102564,Puma,Men Fluorescent Green Velocity Nitro 2 Running...,4.3,58,11999.0,25.0,"""₹11,999.00""",INR,http://assets.myntassets.com/assets/images/191...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,Omn███ch ███ail███,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...",NaN,"11t███loo███Fla█████████6, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1399 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
27,11400234,Yuuki,Men Charcoal Grey Mesh Walking Shoes,3.9,38,2499.0,72.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":4,""2_stars"":3,""3_stars"":5,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""26.7cm"",""value_name"":""To...","[""rw-11400234_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
28,14323336,TRASE,Women Pink & Yellow Mesh Running Shoes,3.9,23,1299.0,NaN,"""₹1,299.00""",INR,http://assets.myntassets.com/assets/images/143...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":5,""4_stars"":...",NaN,NaN,"[{""size"":""4"",""value"":""22.5cm"",""value_name"":""To...","[""rw-14323336_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
29,19402102,U.S. Polo Assn.,Men Off White CRESK Walking Shoes,4.0,124,4999.0,50.0,"""₹4,999.00""",INR,http://assets.myntassets.com/assets/images/194...,...,"{""1_star"":22,""2_stars"":3,""3_stars"":6,""4_stars""...",NaN,NaN,"[{""size"":""6"",""value"":""26.63cm"",""value_name"":""T...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
30,14208394,TRASE,Boys Black & White Relax-I Running Shoes,4.5,13,999.0,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/142...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""8-9Y"",""value"":""21.0cm"",""value_name"":...","[""rw-14208394_cae700""]",NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
31,16880520,PUMA Hoops,Men Red Triple Mid Basketball Shoes,4.1,24,8999.0,55.0,"""₹4,049.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
32,18356356,Nautica,Men Colourblocked & Woven Design Running Shoes,4.4,109,5499.0,60.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":8,""2_stars"":1,""3_stars"":5,""4_stars"":...",NaN,Tru███t C███erc███,"[{""size"":""6""},{""size"":""10""},{""size"":""9""},{""siz...","[""rw-18356356_cae700""]",1 s███loo███Cab█████████-01███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
33,18906230,Skechers,Women Black GO WALK STRETCH FIT-SPECIAL D Shoes,4.5,127,7499.0,40.0,"""₹4,499.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":2,""3_stars"":6,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
34,18373464,ADIDAS,Men Black Woven Design Hailcon Running Shoes,4.1,113,3599.0,NaN,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":12,""2_stars"":2,""3_stars"":13,""4_stars...",NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-18373464_cae700""]","1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
35,16824638,Puma,Women Purple Electrify Nitro Turn Running Shoes,4.3,14,9999.0,50.0,"""₹4,999.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,Pum███por███Ind█████████td.█████████,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...",NaN,Pum███por███Ind█████████d/ ███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
36,18374802,ADIDAS,Women Black Woven Design SL20 X Marimekko Runn...,4.5,21,12999.0,NaN,"""₹12,999.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""4"",""value"":""22.5cm"",""value_name"":""To...",NaN,"1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
37,16824670,Puma,Women Black Run XX Nitro Running Shoes,4.1,31,9999.0,45.0,"""₹5,499.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,Omn███ch ███ail███,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...",NaN,"11t███loo███Fla█████████6, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
38,18374200,ADIDAS,Men Black & White Woven Design Ultraboost 5.0 ...,3.9,15,16999.0,NaN,"""₹10,199.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-18374200_cae700""]","1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
39,18374286,ADIDAS,Men White & Maroon Mickey Mouse Print Grand Co...,4.2,22,5999.0,NaN,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-18374286_cae700""]","1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
40,18382842,WROGN ACTIVE,Men Grey & Orange Woven Design Walking Shoes,3.7,142,3599.0,60.0,"""₹1,439.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":26,""2_stars"":8,""3_stars"":12,""4_stars...",NaN,Sup███om ███,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
41,18373646,ADIDAS,Men Black Woven Design Immute Running Shoes,4.3,319,3799.0,35.0,"""₹2,469.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":21,""2_stars"":5,""3_stars"":25,""4_stars...",NaN,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-18373646_cae700"",""https://videos.myntasse...","1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes

**<h1 style="color:green;">Question 2: Explore Data (head/tail, shape, columns, data types)</h1>**

**In this step, the structure and basic information of the dataset are explored.**

In [4]:
csv_1.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17745816,Lancer,Men Navy Blue Textile Running Non-Marking Shoes,4.0,6,1999.0,40.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/177...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""26.4cm"",""value_name"":""To...",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
1,17631178,Slazenger,Men White Woven Design Walking Shoes,3.7,127,3599.0,NaN,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":22,""2_stars"":10,""3_stars"":13,""4_star...",NaN,Tru███m R███il,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...","[""rw-17631178_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
2,13686682,Campus,Women White Mesh Walking Shoes,4.1,452,799.0,6.0,"""₹751.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":31,""2_stars"":18,""3_stars"":56,""4_star...",NaN,CAM███ AC███EWE█████████D,"[{""size"":""4"",""value"":""24.8cm"",""value_name"":""To...",NaN,Kha███ No███/25█████████ark███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
3,14480064,AfroJack,Men Black Textile Long Distance Running Non-Ma...,3.1,46,3995.0,80.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":14,""2_stars"":3,""3_stars"":6,""4_stars""...",NaN,WIN███INT███ATI██████,"[{""size"":""7"",""value"":""27.0cm"",""value_name"":""To...","[""rw-14480064_cae700""]","PLO███O. ███18,█████████RJE███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
4,10667394,Campus,Men Navy Blue Mesh Madrid Running Shoes,4.1,35,1499.0,37.0,"""₹944.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":3,""4_stars"":...",NaN,CAM███ AC███EWE█████████D,"[{""size"":""6"",""value"":""26.2cm"",""value_name"":""To...",NaN,Kha███ No███/25█████████ark███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes

In [5]:
csv_1.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
46,18374614,ADIDAS,Women Navy Blue & Orange Ultraboost 22 X Marim...,4.3,11,18999.0,25.0,"""₹14,249.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Fla███tar███mme██████,"[{""size"":""4"",""value"":""22.5cm"",""value_name"":""To...",NaN,"1st███oor███abi█████████02,███████████████████...",NaN,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
47,16305908,Campus,Unisex Kids Navy Blue Mesh Running Shoes,4.3,23,1399.0,10.0,"""₹1,259.00""",INR,http://assets.myntassets.com/assets/images/163...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,CAM███ AC███EWE█████████D,"[{""size"":""7-8Y"",""value"":""23.0cm"",""value_name"":...",NaN,Kha███ No███/25█████████ark███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
48,16279696,Forever Glam by Pantaloons,Women Yellow Textile Running Non-Marking Shoes,4.3,6,1699.0,38.0,"""₹1,053.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Wes███ry ███din█████████d_P████████████,"[{""size"":""3"",""value"":""22.5cm"",""value_name"":""To...",NaN,Wes███ry ███din█████████e L███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
49,13072098,Puma,Unisex Grey Orange Flash Running Shoes,4.7,7,4499.0,45.0,"""₹2,474.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Omn███ch ███ail███,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...","[""rw-13072098_cae700""]","11t███loo███Fla█████████6, ███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
50,19298764,Campus,Unisex Kids Yellow Mesh Running Shoes,4.6,71,1299.0,10.0,"""₹909.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,Ret███Net███,"[{""size"":""7-8Y"",""value"":""23.0cm"",""value_name"":...",NaN,Blo███B-1███abi█████████-24███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes

In [6]:
csv_1.shape

(51, 24)

In [7]:
csv_1.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [8]:
csv_1.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said       float64
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

**<h1 style="color:orange;">Question 3: Handle Missing Values (identify, fill/drop)</h1>**

**In this step, missing values are identified and handled using appropriate methods.**

In [10]:
csv_1.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                  23
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       51
seller_name               14
sizes                      0
videos                    21
seller_information        14
variations                32
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [12]:
csv_1.fillna("Not Available", inplace=True)

In [17]:
csv_1.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

**<h1 style="color:purple;">Question 4: Perform Basic Operations (filter rows, select columns)</h1>**

**In this step, basic operations such as selecting columns and filtering rows are performed on the dataset.**

In [20]:
csv_1[csv_1['rating'] > 4]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
2,13686682,Campus,Women White Mesh Walking Shoes,4.1,452,799.0,6.0,"""₹751.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":31,""2_stars"":18,""3_stars"":56,""4_star...",Not Available,CAM███ AC███EWE█████████D,"[{""size"":""4"",""value"":""24.8cm"",""value_name"":""To...",Not Available,Kha███ No███/25█████████ark███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
4,10667394,Campus,Men Navy Blue Mesh Madrid Running Shoes,4.1,35,1499.0,37.0,"""₹944.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":3,""4_stars"":...",Not Available,CAM███ AC███EWE█████████D,"[{""size"":""6"",""value"":""26.2cm"",""value_name"":""To...",Not Available,Kha███ No███/25█████████ark███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
5,20071104,ADIDAS,Men Striped Amalgo M Running Shoes,4.5,149,4299.0,Not Available,"""₹2,794.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":5,""2_stars"":3,""3_stars"":8,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20071104_cae700""]","1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
6,20072084,ADIDAS,Women Woven Design Runfalcon 3.0 Running Shoes,4.1,22,5999.0,Not Available,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":4,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""4"",""value"":""22.5cm"",""value_name"":""To...","[""rw-20072084_cae700""]","1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
8,20071558,ADIDAS,Men Striped Pep Run M Running Shoes,4.1,231,3599.0,Not Available,"""₹2,339.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":23,""2_stars"":14,""3_stars"":15,""4_star...",Not Available,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...",Not Available,"1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
9,20071402,ADIDAS,Men Rokr Trail Trekking Shoes,4.5,149,4599.0,Not Available,"""₹4,599.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":5,""2_stars"":5,""3_stars"":9,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20071402_cae700""]","1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
10,20070948,ADIDAS,Men Hitrail Mid WPN Trekking Shoes,4.1,52,5999.0,Not Available,"""₹5,999.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":3,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20070948_cae700""]","1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
11,20070966,ADIDAS,Men Colourblocked Hikelacer Trekking Shoes,4.2,36,4799.0,Not Available,"""₹2,879.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":5,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-20070966_cae700""]","1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
13,20071236,ADIDAS,Unisex Printed Predator Accuracy.4 Football Shoes,4.3,57,5299.0,Not Available,"""₹5,299.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":5,""2_stars"":3,""3_stars"":2,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""4"",""value"":""22.5cm"",""value_name"":""To...",Not Available,"1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
15,14208408,TRASE,Boys Navy Blue & White Sand-I Running Shoes,4.2,20,999.0,Not Available,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/142...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",Not Available,Not Available,"[{""size"":""8-9Y"",""value"":""21.0cm"",""value_name"":...","[""rw-14208408_cae700""]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
16,11441718,Duke,Men Black & Red Woven Design Running Shoes,4.2,50,2695.0,75.0,"""₹2,695.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":8,""4_stars"":...",Not Available,Not Available,"[{""size"":""6"",""value"":""25.04cm"",""value_name"":""T...","[""rw-11441718_cae700""]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
18,11627996,Yuuki,Men Black Mesh Running Shoes,4.2,56,2999.0,67.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":3,""2_stars"":3,""3_stars"":3,""4_stars"":...",Not Available,Not Available,"[{""size"":""6"",""value"":""26.7cm"",""value_name"":""To...","[""rw-11627996_cae700""]",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
21,11986876,FAUSTO,Men Blue Mesh Walking Shoes,4.3,9,899.0,1.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/119...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""6"",""value"":""25.5cm"",""value_name"":""To...","[""rw-11986876_cae700""]",Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
23,19334942,ELEVAR,Men Grey FLYBOLT Running Sports Shoes,4.3,6,5490.0,Not Available,"""₹5,490.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Not Available,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...","[""rw-19334942_cae700""]",Not Available,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
24,13484354,Puma,Women Black Eternity Nitro Running Shoes,4.3,19,12999.0,Not Available,"""₹12,999.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Not Available,Pum███por███Ind█████████td.█████████,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...","[""rw-13484354_cae700""]",Pum███por███Ind█████████d/ ███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
25,11960808,Campus,Men Navy Blue Running Shoes,4.2,76,1499.0,56.0,"""₹659.00""",INR,http://assets.myntassets.com/assets/images/119...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":10,""4_stars""...",Not Available,CAM███ AC███EWE█████████D,"[{""size"":""6"",""value"":""26.2cm"",""value_name"":""To...","[""rw-11960808_cae700""]",Kha███ No███/25█████████ark███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
26,19102564,Puma,Men Fluorescent Green Velocity Nitro 2 Running...,4.3,58,11999.0,25.0,"""₹11,999.00""",INR,http://assets.myntassets.com/assets/images/191...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":1,""4_stars"":...",Not Available,Omn███ch ███ail███,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...",Not Available,"11t███loo███Fla█████████6, ███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1399 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
30,14208394,TRASE,Boys Black & White Relax-I Running Shoes,4.5,13,999.0,Not Available,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/142...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",Not Available,Not Available,"[{""size"":""8-9Y"",""value"":""21.0cm"",""value_name"":...","[""rw-14208394_cae700""]",Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
31,16880520,PUMA Hoops,Men Red Triple Mid Basketball Shoes,4.1,24,8999.0,55.0,"""₹4,049.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":0,""4_stars"":...",Not Available,Sup███om ███,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...",Not Available,Plo███o- ███ 1s█████████Sui███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
32,18356356,Nautica,Men Colourblocked & Woven Design Running Shoes,4.4,109,5499.0,60.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":8,""2_stars"":1,""3_stars"":5,""4_stars"":...",Not Available,Tru███t C███erc███,"[{""size"":""6""},{""size"":""10""},{""size"":""9""},{""siz...","[""rw-18356356_cae700""]",1 s███loo███Cab█████████-01███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
33,18906230,Skechers,Women Black GO WALK STRETCH FIT-SPECIAL D Shoes,4.5,127,7499.0,40.0,"""₹4,499.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":2,""3_stars"":6,""4_stars"":...",Not Available,Sup███om ███,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
34,18373464,ADIDAS,Men Black Woven Design Hailcon Running Shoes,4.1,113,3599.0,Not Available,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":12,""2_stars"":2,""3_stars"":13,""4_stars...",Not Available,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-18373464_cae700""]","1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
35,16824638,Puma,Women Purple Electrify Nitro Turn Running Shoes,4.3,14,9999.0,50.0,"""₹4,999.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",Not Available,Pum███por███Ind█████████td.█████████,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...",Not Available,Pum███por███Ind█████████d/ ███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
36,18374802,ADIDAS,Women Black Woven Design SL20 X Marimekko Runn...,4.5,21,12999.0,Not Available,"""₹12,999.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""4"",""value"":""22.5cm"",""value_name"":""To...",Not Available,"1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
37,16824670,Puma,Women Black Run XX Nitro Running Shoes,4.1,31,9999.0,45.0,"""₹5,499.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":3,""4_stars"":...",Not Available,Omn███ch ███ail███,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...",Not Available,"11t███loo███Fla█████████6, ███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
39,18374286,ADIDAS,Men White & Maroon Mickey Mouse Print Grand Co...,4.2,22,5999.0,Not Available,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-18374286_cae700""]","1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
41,18373646,ADIDAS,Men Black Woven Design Immute Running Shoes,4.3,319,3799.0,35.0,"""₹2,469.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":21,""2_stars"":5,""3_stars"":25,""4_stars...",Not Available,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-18373646_cae700"",""https://videos.myntasse...","1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
42,18373380,ADIDAS,Men Grey Woven Design Adi Dash Running Shoes,4.2,73,4799.0,35.0,"""₹3,119.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":5,""2_stars"":2,""3_stars"":7,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...",Not Available,"1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
43,16864474,Puma,Men Orange & White Spike 22.2 Cricket Shoes,5.0,3,6999.0,20.0,"""₹5,599.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Not Available,Pum███por███Ind█████████td.█████████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...",Not Available,Pum███por███Ind█████████d/ ███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
44,18374978,ADIDAS,Women White Solid Courtpoint Tennis Shoes,4.4,94,4999.0,Not Available,"""₹3,249.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":5,""2_stars"":3,""3_stars"":5,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""4"",""value"":""22.5cm"",""value_name"":""To...",Not Available,"1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
45,18906226,Skechers,Women Black GO WALK 4-ARRAY Shoes,4.4,93,6499.0,40.0,"""₹3,899.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":6,""3_stars"":3,""4_stars"":...",Not Available,Sup███om ███,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...","[""rw-18906226_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
46,18374614,ADIDAS,Women Navy Blue & Orange Ultraboost 22 X Marim...,4.3,11,18999.0,25.0,"""₹14,249.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",Not Available,Fla███tar███mme██████,"[{""size"":""4"",""value"":""22.5cm"",""value_name"":""To...",Not Available,"1st███oor███abi█████████02,███████████████████...",Not Available,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
47,16305908,Campus,Unisex Kids Navy Blue Mesh Running Shoes,4.3,23,1399.0,10.0,"""₹1,259.00""",INR,http://assets.myntassets.com/assets/images/163...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",Not Available,CAM███ AC███EWE█████████D,"[{""size"":""7-8Y"",""value"":""23.0cm"",""value_name"":...",Not Available,Kha███ No███/25█████████ark███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
48,16279696,Forever Glam by Pantaloons,Women Yellow Textile Running Non-Marking Shoes,4.3,6,1699.0,38.0,"""₹1,053.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",Not Available,Wes███ry ███din█████████d_P████████████,"[{""size"":""3"",""value"":""22.5cm"",""value_name"":""To...",Not Available,Wes███ry ███din█████████e L███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
49,13072098,Puma,Unisex Grey Orange Flash Running Shoes,4.7,7,4499.0,45.0,"""₹2,474.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",Not Available,Omn███ch ███ail███,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...","[""rw-13072098_cae700""]","11t███loo███Fla█████████6, ███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
50,19298764,Campus,Unisex Kids Yellow Mesh Running Shoes,4.6,71,1299.0,10.0,"""₹909.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",Not Available,Ret███Net███,"[{""size"":""7-8Y"",""value"":""23.0cm"",""value_name"":...",Not Available,Blo███B-1███abi█████████-24███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes

In [22]:
csv_1[['title', 'rating', 'initial_price']]

                         title  rating  initial_price
0                       Lancer     4.0         1999.0
1                    Slazenger     3.7         3599.0
2                       Campus     4.1          799.0
3                     AfroJack     3.1         3995.0
4                       Campus     4.1         1499.0
5                       ADIDAS     4.5         4299.0
6                       ADIDAS     4.1         5999.0
7                       ADIDAS     3.2        11999.0
8                       ADIDAS     4.1         3599.0
9                       ADIDAS     4.5         4599.0
10                      ADIDAS     4.1         5999.0
11                      ADIDAS     4.2         4799.0
12                        UCLA     3.7         4199.0
13                      ADIDAS     4.3         5299.0
14                UNDER ARMOUR     3.9        13499.0
15                       TRASE     4.2          999.0
16                        Duke     4.2         2695.0
17                      ELEVAR     3.7         6490.0
18                       Yuuki     4.2         2999.0
19                      FAUSTO     3.9          899.0
20                      ELEVAR     3.2         5490.0
21                      FAUSTO     4.3          899.0
22                      ELEVAR     3.0         5490.0
23                      ELEVAR     4.3         5490.0
24                        Puma     4.3        12999.0
25                      Campus     4.2         1499.0
26                        Puma     4.3        11999.0
27                       Yuuki     3.9         2499.0
28                       TRASE     3.9         1299.0
29             U.S. Polo Assn.     4.0         4999.0
30                       TRASE     4.5          999.0
31                  PUMA Hoops     4.1         8999.0
32                     Nautica     4.4         5499.0
33                    Skechers     4.5         7499.0
34                      ADIDAS     4.1         3599.0
35                        Puma     4.3         9999.0
36                      ADIDAS     4.5        12999.0
37                        Puma     4.1         9999.0
38                      ADIDAS     3.9        16999.0
39                      ADIDAS     4.2         5999.0
40                WROGN ACTIVE     3.7         3599.0
41                      ADIDAS     4.3         3799.0
42                      ADIDAS     4.2         4799.0
43                        Puma     5.0         6999.0
44                      ADIDAS     4.4         4999.0
45                    Skechers     4.4         6499.0
46                      ADIDAS     4.3        18999.0
47                      Campus     4.3         1399.0
48  Forever Glam by Pantaloons     4.3         1699.0
49                        Puma     4.7         4499.0
50                      Campus     4.6         1299.0

**<h1 style = "color:red;">Question 5: Remove Duplicates</h1>**

**In this step, duplicate rows are identified and removed from the dataset.**

In [25]:
csv_1.duplicated().sum()

np.int64(0)

In [24]:
csv_1.drop_duplicates(inplace=True)
print("Duplicates removed successfully!")

Duplicates removed successfully!

**<h1 style ="color:Brown;">Question 6: Create a Derived Column (total_amount = price * quantity)</h1>**

**In this step, a new column named total_amount is created using price and quantity columns.**

In [27]:
#converting discount column into numeric datatype
# Required for mathematical calculations
csv_1['discount'] = pd.to_numeric(csv_1['discount'],errors='coerce')

In [28]:
# Replacing missing discount values with 0
# Prevents calculation errors

csv_1['discount'] = csv_1['discount'].fillna(0)

In [29]:
# Creating price, quantity, and total_amount columns

csv_1['price'] = csv_1['initial_price'] - csv_1['discount']

csv_1['quantity'] = csv_1['ratings_count']

csv_1['total_amount'] = csv_1['price'] * csv_1['quantity']

In [30]:
#Displaying derived columns

csv_1[['price','quantity','total_amount']].head()

    price  quantity  total_amount
0  1959.0         6       11754.0
1  3599.0       127      457073.0
2   793.0       452      358436.0
3  3915.0        46      180090.0
4  1462.0        35       51170.0

**<h1 style="color:darkblue;">Question 7: Save the Cleaned Dataset as a New CSV File</h1>**

**In this step, the cleaned dataset is saved as a new CSV file for future analysis.**

In [31]:
csv_1.to_csv("cleaned_sports_shoes.csv", index=False)

In [32]:
cleaned_data = pd.read_csv("cleaned_sports_shoes.csv")

cleaned_data.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,sizes,videos,seller_information,variations,best_offer,more_offers,category,price,quantity,total_amount
0,17745816,Lancer,Men Navy Blue Textile Running Non-Marking Shoes,4.0,6,1999.0,40.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/177...,...,"[{""size"":""6"",""value"":""26.4cm"",""value_name"":""To...",Not Available,Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes,1959.0,6,11754.0
1,17631178,Slazenger,Men White Woven Design Walking Shoes,3.7,127,3599.0,0.0,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...","[""rw-17631178_cae700""]",Sho███o. ███-10█████████enu███████████████████...,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes,3599.0,127,457073.0
2,13686682,Campus,Women White Mesh Walking Shoes,4.1,452,799.0,6.0,"""₹751.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"[{""size"":""4"",""value"":""24.8cm"",""value_name"":""To...",Not Available,Kha███ No███/25█████████ark███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes,793.0,452,358436.0
3,14480064,AfroJack,Men Black Textile Long Distance Running Non-Ma...,3.1,46,3995.0,80.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""size"":""7"",""value"":""27.0cm"",""value_name"":""To...","[""rw-14480064_cae700""]","PLO███O. ███18,█████████RJE███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes,3915.0,46,180090.0
4,10667394,Campus,Men Navy Blue Mesh Madrid Running Shoes,4.1,35,1499.0,37.0,"""₹944.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""size"":""6"",""value"":""26.2cm"",""value_name"":""To...",Not Available,Kha███ No███/25█████████ark███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes,1462.0,35,51170.0

In [25]:
csv_1.to_csv(r"c:\Users\ANUJ\Downloads\cleaned_sports_shoes.csv", index=False)

In [26]:
import os
print(os.path.abspath("cleaned_sports_shoes.csv"))

C:\Users\ANUJ\cleaned_sports_shoes.csv

In [27]:
os.path.splitext("cleaned_sports_shoes.csv")

('cleaned_sports_shoes', '.csv')

**<h1 style = "color:black;"> Brief Summary </h1>**



In this assignment, data was imported and analyzed using Pandas. Different Pandas functions were used to examine the dataset structure and identify missing values. Missing data was handled using suitable techniques such as mean, mode, and fill operations. Data filtering, column selection, and duplicate removal were also carried out to improve data quality. A new column called total_amount was generated from existing columns, and the cleaned dataset was exported into a new CSV file for further use and analysis.